/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto;

import Estructuras.Lista;
import Estructuras.Nodo;
import Estructuras.NodoLista;
import javax.swing.JOptionPane;

/**
 *
 * @author maria
 */
public class InterfazBuscarNombre extends javax.swing.JFrame {

    /**
     * Creates new form InterfazBuscarNombre
     */
    private InterfazSeleccion interfazPrincipal;

    public InterfazBuscarNombre(InterfazSeleccion interfazPrincipal) {
        initComponents();
        this.interfazPrincipal = interfazPrincipal;
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreIngresado = new javax.swing.JTextField();
        BuscarNombre = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Consola = new javax.swing.JTextArea();
        Volver = new javax.swing.JButton();
        listaRespuesta = new javax.swing.JComboBox<>();
        verInfo = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel1.setText("Ingresa el nombre de la persona a buscar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 360, -1));

        nombreIngresado.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        nombreIngresado.setText("Inserta el nombre o mote");
        nombreIngresado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreIngresadoActionPerformed(evt);
            }
        });
        jPanel1.add(nombreIngresado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, -1));

        BuscarNombre.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        BuscarNombre.setText("Buscar Nombre");
        BuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarNombreActionPerformed(evt);
            }
        });
        jPanel1.add(BuscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        Consola.setColumns(20);
        Consola.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        Consola.setRows(5);
        jScrollPane1.setViewportView(Consola);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 240, 150));

        Volver.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        Volver.setText("Volver al inicio");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jPanel1.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        listaRespuesta.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        listaRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaRespuestaActionPerformed(evt);
            }
        });
        jPanel1.add(listaRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        verInfo.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        verInfo.setText("Ver Informacion");
        verInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verInfoActionPerformed(evt);
            }
        });
        jPanel1.add(verInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarNombreActionPerformed
        // TODO add your handling code here:
        String respuestaNombre = this.nombreIngresado.getText();
        if (respuestaNombre.equals("")) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un texto valido");
        } else {
            Lista respuesta = InterfazSeleccion.arbol.buscarPorNombreyMote(respuestaNombre);
            NodoLista aux = respuesta.getPrimero();
            this.listaRespuesta.removeAllItems();
            while (aux != null) {
                this.listaRespuesta.addItem(aux.getDatos());
                aux = aux.getPnext();
            }
        }
    }//GEN-LAST:event_BuscarNombreActionPerformed

    private void nombreIngresadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreIngresadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreIngresadoActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        this.interfazPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void listaRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaRespuestaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_listaRespuestaActionPerformed

    private void verInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verInfoActionPerformed
        // TODO add your handling code here:
        Object respuestakta = this.listaRespuesta.getSelectedItem();
        if (respuestakta == null) {
            JOptionPane.showMessageDialog(null, "Selecciona una de las opciones");
        } else {
            Nodo respuesta = InterfazSeleccion.tabla.buscarPorKta(respuestakta.toString());
            this.Consola.setText(respuesta.gettInfo().toString());

        }
    }//GEN-LAST:event_verInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazBuscarNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazBuscarNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazBuscarNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazBuscarNombre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazBuscarNombre(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarNombre;
    private javax.swing.JTextArea Consola;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> listaRespuesta;
    private javax.swing.JTextField nombreIngresado;
    private javax.swing.JButton verInfo;
    // End of variables declaration//GEN-END:variables
}
